spring:
  data:
    redis:
      database: ${REDIS_DATABASE:0}
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}

  rsocket:
    server:
      mapping-path: /rsocket
      transport: websocket

projectbirdnest:
  ndz:
    origin-x: 250000
    origin-y: 250000
    radius: 100000
